### ISSUE TITLE
Undefined method in pupdate_to_ruby_time

### ISSUE THREAD

**Issue by AndreCaseyScott** [maxjacobson/flee_to_md#1]
Trying to run on a Wordpress export XML file. Know it's not _officially_ supported, but figured that SquareSpace exports Wordpress compatible files so it shouldn't be horrible to bang it into submission.

Unfortunately when I run `flee_to_md wp.xml` it errors out with

```
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/flee_to_md-0.1.1/lib/flee_to_md.rb:120:in `pubdate_to_ruby_time': undefined method `[]' for nil:NilClass (NoMethodError)
```

There was other output but it seemed like it was listing precursor methods. Can list those too if it helps.

Wondering if there is sometime I can change either in my `wp.xml` file or in the gem itself to hack this out.

Thanks!

**Comment by AndreCaseyScott** [comment]
If it helps, I have also attempted this on a SquareSpace export and the same error occurs. Maybe they changed the XML format? unsure....

**Comment by maxjacobson** [comment]
that error means the date is formatted differently from how I expected. How are dates formatted in your XML file?

flee_to_md [assumes](https://github.com/maxjacobson/flee_to_md/blob/master/lib/flee_to_md.rb#L117) this format: `Fri, 12 Oct 2012 17:58:03 +0000`

which it seems is a too-rigid assumption!

If you wouldn't mind sending it to me I could try running it and fix the bugs that come up. I've been half-heartedly meaning to totally rewrite this thing to support one or two more input and output formats and maybe this is a good start? feel free to email

**Comment by AndreCaseyScott** [comment]
From what I can tell, each post has 3 date fields associated with it:
`<pubDate>Mon, 27 May 2013 19:13:11 +0000</pubDate>`
`<wp:post_date>2013-05-26 20:44:00</wp:post_date>`
`<wp:post_date_gmt>2013-05-27 03:44:00</wp:post_date_gmt>`

Yet it looks like the flee_to_md.rb is only selecting the `<pubDate>` which is in the right format. 

Yea, that would be neat! I'm planning on using this script to migrate my content to a Statamic site, but I'm sure folks could use it to migrate to different platforms too, if they are sick of Wordpress/SquareSpace.

I'll email the wordpress.xml export and my attempt do some trickery with SquareSpace exports. (I imported my site to SquareSpace and then exported that to try and get flee_to_md to work. no go). Seems the SquareSpace xml has a lot less complexity. Uses the Wordpress XML format, but strangely different.
